name: Build only

on:
  push:
    branches:
      - develop

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4
        with:
          workspaces: |
            ./rust -> ./rust/target

      - name: Install WebAssembly target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli & wasm-opt
        run: |
          cargo install wasm-bindgen-cli --version 0.2.121
          cargo install wasm-opt --version 0.116.1

      - name: Compile to wasm
        run: |
          cd ./rust
          cargo build --release --lib

      - name: Execute wasm-bindgen & Optimize wasm
        run: |
          cd ./rust
          echo "execute wasm-bindgen..."
          wasm-bindgen --out-dir ../src/lib/wasm --typescript --target web ./target/wasm32-unknown-unknown/release/wasm_part.wasm
          cd ../src/lib/wasm
          echo "optimize wasm using wasm-opt..."
          wasm-opt ./wasm_part_bg.wasm -o ./opted.wasm -O
          mv ./opted.wasm ./wasm_part_bg.wasm

      - name: Build SvelteKit
        run: pnpm run build
